# Generated by Django 5.0.7 on 2026-08-26 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuestResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tell_me_something', models.TextField(blank=True)),
                ('favorite_color', models.CharField(blank=True, max_length=100)),
                ('complete_word', models.CharField(blank=True, max_length=100)),
                ('favorite_number', models.CharField(blank=True, max_length=50)),
                ('keep_data', models.BooleanField()),
                ('create_profile', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
